apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: default
data:
  config.yaml: |
    ingress:
      - hostname: gitea.ahmadfaisal.space
        service: http://gitea.default.svc.cluster.local:3000
      
      - hostname: ssh-gitea.ahmadfaisal.space
        service: ssh://gitea.default.svc.cluster.local:2222
      
      - hostname: jenkins.ahmadfaisal.space
        service: http://jenkins.jenkins.svc.cluster.local:8080
        
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: default
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:1815-d7c62aed71e2
          args:
            - tunnel
            - --config /etc/cloudflared/config/config.yaml
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-credentials
                  key: token
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: cloudflared-config
