apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: default
  labels:
    app: cloudflared
data:
  config.yaml:
    tunnel: 9ed1e154-1856-4c11-ba08-471262ac037c
    credentials-file: tunnel-credentials

    ingress:
      - hostname: gitea.ahmadfaisal.space
        service: http://gitea.default.svc.cluster.local:3000

      - hostname: jenkins.ahmadfaisal.space
        service: http://jenkins.jenkins.svc.cluster.local:8080

      - service: http_status:404
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:1815-d7c62aed71e2
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-credentials
                  key: token
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
